<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>R for Psych</title>
  <meta name="description" content="An introduction to data management and analysis for psychological research using R.">
  <meta name="generator" content="bookdown 0.6 and GitBook 2.6.7">

  <meta property="og:title" content="R for Psych" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="http://glennwilliams.me/r4psych/" />
  
  <meta property="og:description" content="An introduction to data management and analysis for psychological research using R." />
  <meta name="github-repo" content="gpwilliams/r4psych" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="R for Psych" />
  
  <meta name="twitter:description" content="An introduction to data management and analysis for psychological research using R." />
  

<meta name="author" content="Glenn Williams">


<meta name="date" content="2018-04-18">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="advanced-statistical-tests.html">
<link rel="next" href="mixed-effects-models.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">R for Psych</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface &amp; Overview</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#installation-and-setup"><i class="fa fa-check"></i><b>1.1</b> Installation and Setup</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#working-directory-and-file-paths"><i class="fa fa-check"></i><b>1.2</b> Working Directory and File Paths</a></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#packages"><i class="fa fa-check"></i><b>1.3</b> Packages</a></li>
<li class="chapter" data-level="1.4" data-path="introduction.html"><a href="introduction.html#objects-and-functions"><i class="fa fa-check"></i><b>1.4</b> Objects and Functions</a></li>
<li class="chapter" data-level="1.5" data-path="introduction.html"><a href="introduction.html#creating-and-accessing-data"><i class="fa fa-check"></i><b>1.5</b> Creating and Accessing Data</a></li>
<li class="chapter" data-level="1.6" data-path="introduction.html"><a href="introduction.html#good-practice"><i class="fa fa-check"></i><b>1.6</b> Good Practice</a><ul>
<li class="chapter" data-level="1.6.1" data-path="introduction.html"><a href="introduction.html#data-checking-tips"><i class="fa fa-check"></i><b>1.6.1</b> Data Checking Tips</a></li>
<li class="chapter" data-level="1.6.2" data-path="introduction.html"><a href="introduction.html#style"><i class="fa fa-check"></i><b>1.6.2</b> Style</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="introduction.html"><a href="introduction.html#exercises"><i class="fa fa-check"></i><b>1.7</b> Exercises</a><ul>
<li class="chapter" data-level="1.7.1" data-path="introduction.html"><a href="introduction.html#question-1"><i class="fa fa-check"></i><b>1.7.1</b> Question 1</a></li>
<li class="chapter" data-level="1.7.2" data-path="introduction.html"><a href="introduction.html#question-2"><i class="fa fa-check"></i><b>1.7.2</b> Question 2</a></li>
<li class="chapter" data-level="1.7.3" data-path="introduction.html"><a href="introduction.html#question-3"><i class="fa fa-check"></i><b>1.7.3</b> Question 3</a></li>
<li class="chapter" data-level="1.7.4" data-path="introduction.html"><a href="introduction.html#question-4"><i class="fa fa-check"></i><b>1.7.4</b> Question 4</a></li>
<li class="chapter" data-level="1.7.5" data-path="introduction.html"><a href="introduction.html#question-5"><i class="fa fa-check"></i><b>1.7.5</b> Question 5</a></li>
<li class="chapter" data-level="1.7.6" data-path="introduction.html"><a href="introduction.html#question-6"><i class="fa fa-check"></i><b>1.7.6</b> Question 6</a></li>
<li class="chapter" data-level="1.7.7" data-path="introduction.html"><a href="introduction.html#question-7"><i class="fa fa-check"></i><b>1.7.7</b> Question 7</a></li>
<li class="chapter" data-level="1.7.8" data-path="introduction.html"><a href="introduction.html#question-8"><i class="fa fa-check"></i><b>1.7.8</b> Question 8</a></li>
<li class="chapter" data-level="1.7.9" data-path="introduction.html"><a href="introduction.html#question-9"><i class="fa fa-check"></i><b>1.7.9</b> Question 9</a></li>
<li class="chapter" data-level="1.7.10" data-path="introduction.html"><a href="introduction.html#question-10"><i class="fa fa-check"></i><b>1.7.10</b> Question 10</a></li>
<li class="chapter" data-level="1.7.11" data-path="introduction.html"><a href="introduction.html#question-11"><i class="fa fa-check"></i><b>1.7.11</b> Question 11</a></li>
<li class="chapter" data-level="1.7.12" data-path="introduction.html"><a href="introduction.html#question-12"><i class="fa fa-check"></i><b>1.7.12</b> Question 12</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html"><i class="fa fa-check"></i><b>2</b> Data Visualisation 1</a><ul>
<li class="chapter" data-level="2.1" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#getting-started"><i class="fa fa-check"></i><b>2.1</b> Getting Started</a><ul>
<li class="chapter" data-level="2.1.1" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#the-star-wars-tibble"><i class="fa fa-check"></i><b>2.1.1</b> The Star Wars Tibble</a></li>
<li class="chapter" data-level="2.1.2" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#plotting-in-ggplot2"><i class="fa fa-check"></i><b>2.1.2</b> Plotting in ggplot2</a></li>
<li class="chapter" data-level="2.1.3" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#cleaning-before-plotting"><i class="fa fa-check"></i><b>2.1.3</b> Cleaning Before Plotting</a></li>
<li class="chapter" data-level="2.1.4" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#changing-your-aesthetics"><i class="fa fa-check"></i><b>2.1.4</b> Changing Your Aesthetics</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#exploring-different-geoms"><i class="fa fa-check"></i><b>2.2</b> Exploring Different Geoms</a><ul>
<li class="chapter" data-level="2.2.1" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#bar-plots"><i class="fa fa-check"></i><b>2.2.1</b> Bar Plots</a></li>
<li class="chapter" data-level="2.2.2" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#box-plots"><i class="fa fa-check"></i><b>2.2.2</b> Box Plots</a></li>
<li class="chapter" data-level="2.2.3" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#violin-plots"><i class="fa fa-check"></i><b>2.2.3</b> Violin Plots</a></li>
<li class="chapter" data-level="2.2.4" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#density-plots"><i class="fa fa-check"></i><b>2.2.4</b> Density Plots</a></li>
<li class="chapter" data-level="2.2.5" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#histograms"><i class="fa fa-check"></i><b>2.2.5</b> Histograms</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#exercises-1"><i class="fa fa-check"></i><b>2.3</b> Exercises</a><ul>
<li class="chapter" data-level="2.3.1" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#main-exercises"><i class="fa fa-check"></i><b>2.3.1</b> Main Exercises</a></li>
<li class="chapter" data-level="2.3.2" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#question-1-1"><i class="fa fa-check"></i><b>2.3.2</b> Question 1</a></li>
<li class="chapter" data-level="2.3.3" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#question-2-1"><i class="fa fa-check"></i><b>2.3.3</b> Question 2</a></li>
<li class="chapter" data-level="2.3.4" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#question-3-1"><i class="fa fa-check"></i><b>2.3.4</b> Question 3</a></li>
<li class="chapter" data-level="2.3.5" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#question-4-1"><i class="fa fa-check"></i><b>2.3.5</b> Question 4</a></li>
<li class="chapter" data-level="2.3.6" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#question-5-1"><i class="fa fa-check"></i><b>2.3.6</b> Question 5</a></li>
<li class="chapter" data-level="2.3.7" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#question-6-1"><i class="fa fa-check"></i><b>2.3.7</b> Question 6</a></li>
<li class="chapter" data-level="2.3.8" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#question-7-1"><i class="fa fa-check"></i><b>2.3.8</b> Question 7</a></li>
<li class="chapter" data-level="2.3.9" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#question-8-1"><i class="fa fa-check"></i><b>2.3.9</b> Question 8</a></li>
<li class="chapter" data-level="2.3.10" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#question-9-1"><i class="fa fa-check"></i><b>2.3.10</b> Question 9</a></li>
<li class="chapter" data-level="2.3.11" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#question-10-1"><i class="fa fa-check"></i><b>2.3.11</b> Question 10</a></li>
<li class="chapter" data-level="2.3.12" data-path="data-visualisation-1.html"><a href="data-visualisation-1.html#additional-exercise"><i class="fa fa-check"></i><b>2.3.12</b> Additional Exercise</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html"><i class="fa fa-check"></i><b>3</b> Data Visualisation 2</a><ul>
<li class="chapter" data-level="3.1" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#customising-your-plots"><i class="fa fa-check"></i><b>3.1</b> Customising Your Plots</a></li>
<li class="chapter" data-level="3.2" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#pirate-plots"><i class="fa fa-check"></i><b>3.2</b> Pirate Plots</a></li>
<li class="chapter" data-level="3.3" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#faceting"><i class="fa fa-check"></i><b>3.3</b> Faceting</a><ul>
<li class="chapter" data-level="3.3.1" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#facet-wrap"><i class="fa fa-check"></i><b>3.3.1</b> Facet Wrap</a></li>
<li class="chapter" data-level="3.3.2" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#facet-grid"><i class="fa fa-check"></i><b>3.3.2</b> Facet Grid</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#calculating-statisitcs-in-ggplot2"><i class="fa fa-check"></i><b>3.4</b> Calculating Statisitcs in ggplot2</a><ul>
<li class="chapter" data-level="3.4.1" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#means-and-error-bars"><i class="fa fa-check"></i><b>3.4.1</b> Means and Error Bars</a></li>
<li class="chapter" data-level="3.4.2" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#model-fits"><i class="fa fa-check"></i><b>3.4.2</b> Model Fits</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#combining-plots"><i class="fa fa-check"></i><b>3.5</b> Combining Plots</a></li>
<li class="chapter" data-level="3.6" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#saving-plots"><i class="fa fa-check"></i><b>3.6</b> Saving Plots</a></li>
<li class="chapter" data-level="3.7" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#exercises-2"><i class="fa fa-check"></i><b>3.7</b> Exercises</a><ul>
<li class="chapter" data-level="3.7.1" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#main-exercises-1"><i class="fa fa-check"></i><b>3.7.1</b> Main Exercises</a></li>
<li class="chapter" data-level="3.7.2" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#question-1-2"><i class="fa fa-check"></i><b>3.7.2</b> Question 1</a></li>
<li class="chapter" data-level="3.7.3" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#question-2-2"><i class="fa fa-check"></i><b>3.7.3</b> Question 2</a></li>
<li class="chapter" data-level="3.7.4" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#question-3-2"><i class="fa fa-check"></i><b>3.7.4</b> Question 3</a></li>
<li class="chapter" data-level="3.7.5" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#question-4-2"><i class="fa fa-check"></i><b>3.7.5</b> Question 4</a></li>
<li class="chapter" data-level="3.7.6" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#question-5-2"><i class="fa fa-check"></i><b>3.7.6</b> Question 5</a></li>
<li class="chapter" data-level="3.7.7" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#question-6-2"><i class="fa fa-check"></i><b>3.7.7</b> Question 6</a></li>
<li class="chapter" data-level="3.7.8" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#question-7-2"><i class="fa fa-check"></i><b>3.7.8</b> Question 7</a></li>
<li class="chapter" data-level="3.7.9" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#question-8-2"><i class="fa fa-check"></i><b>3.7.9</b> Question 8</a></li>
<li class="chapter" data-level="3.7.10" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#question-9-2"><i class="fa fa-check"></i><b>3.7.10</b> Question 9</a></li>
<li class="chapter" data-level="3.7.11" data-path="data-visualisation-2.html"><a href="data-visualisation-2.html#additional-exercise-1"><i class="fa fa-check"></i><b>3.7.11</b> Additional Exercise</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html"><i class="fa fa-check"></i><b>4</b> Data Manipulation 1</a><ul>
<li class="chapter" data-level="4.1" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#getting-started-1"><i class="fa fa-check"></i><b>4.1</b> Getting Started</a></li>
<li class="chapter" data-level="4.2" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#data-formats"><i class="fa fa-check"></i><b>4.2</b> Data Formats</a><ul>
<li class="chapter" data-level="4.2.1" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#loading-data"><i class="fa fa-check"></i><b>4.2.1</b> Loading Data</a></li>
<li class="chapter" data-level="4.2.2" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#wide-and-long-data"><i class="fa fa-check"></i><b>4.2.2</b> Wide and Long Data</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#reformatting-data"><i class="fa fa-check"></i><b>4.3</b> Reformatting Data</a><ul>
<li class="chapter" data-level="4.3.1" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#gathering-data"><i class="fa fa-check"></i><b>4.3.1</b> Gathering Data</a></li>
<li class="chapter" data-level="4.3.2" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#separating-columns"><i class="fa fa-check"></i><b>4.3.2</b> Separating Columns</a></li>
<li class="chapter" data-level="4.3.3" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#spreading-data"><i class="fa fa-check"></i><b>4.3.3</b> Spreading Data</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#joins"><i class="fa fa-check"></i><b>4.4</b> Joins</a><ul>
<li class="chapter" data-level="4.4.1" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#mutating-joins"><i class="fa fa-check"></i><b>4.4.1</b> Mutating Joins</a></li>
<li class="chapter" data-level="4.4.2" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#filtering-joins"><i class="fa fa-check"></i><b>4.4.2</b> Filtering Joins</a></li>
<li class="chapter" data-level="4.4.3" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#binding-joins"><i class="fa fa-check"></i><b>4.4.3</b> Binding Joins</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#checking-for-unique-and-duplicate-information"><i class="fa fa-check"></i><b>4.5</b> Checking for Unique and Duplicate Information</a></li>
<li class="chapter" data-level="4.6" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#exercises-3"><i class="fa fa-check"></i><b>4.6</b> Exercises</a><ul>
<li class="chapter" data-level="4.6.1" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#introduction-and-setup"><i class="fa fa-check"></i><b>4.6.1</b> Introduction and Setup</a></li>
<li class="chapter" data-level="4.6.2" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#long-and-wide-data"><i class="fa fa-check"></i><b>4.6.2</b> Long and Wide Data</a></li>
<li class="chapter" data-level="4.6.3" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#uniting-and-separating-columns"><i class="fa fa-check"></i><b>4.6.3</b> Uniting and Separating Columns</a></li>
<li class="chapter" data-level="4.6.4" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#mutating-joins-1"><i class="fa fa-check"></i><b>4.6.4</b> Mutating Joins</a></li>
<li class="chapter" data-level="4.6.5" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#filtering-joins-1"><i class="fa fa-check"></i><b>4.6.5</b> Filtering Joins</a></li>
<li class="chapter" data-level="4.6.6" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#binding-joins-1"><i class="fa fa-check"></i><b>4.6.6</b> Binding Joins</a></li>
<li class="chapter" data-level="4.6.7" data-path="data-manipulation-1.html"><a href="data-manipulation-1.html#checking-for-duplicates"><i class="fa fa-check"></i><b>4.6.7</b> Checking for Duplicates</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html"><i class="fa fa-check"></i><b>5</b> Data Manipulation 2</a><ul>
<li class="chapter" data-level="5.1" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#getting-started-2"><i class="fa fa-check"></i><b>5.1</b> Getting Started</a></li>
<li class="chapter" data-level="5.2" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#understanding-our-data"><i class="fa fa-check"></i><b>5.2</b> Understanding our Data</a></li>
<li class="chapter" data-level="5.3" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#preparing-our-data"><i class="fa fa-check"></i><b>5.3</b> Preparing our Data</a></li>
<li class="chapter" data-level="5.4" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#selecting-columns"><i class="fa fa-check"></i><b>5.4</b> Selecting Columns</a><ul>
<li class="chapter" data-level="5.4.1" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#renaming-and-reordering-columns"><i class="fa fa-check"></i><b>5.4.1</b> Renaming and Reordering Columns</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#creating-and-changing-columns"><i class="fa fa-check"></i><b>5.5</b> Creating and Changing Columns</a></li>
<li class="chapter" data-level="5.6" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#filtering-to-observations"><i class="fa fa-check"></i><b>5.6</b> Filtering to Observations</a><ul>
<li class="chapter" data-level="5.6.1" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#filtering-with-logical-operations"><i class="fa fa-check"></i><b>5.6.1</b> Filtering with Logical Operations</a></li>
<li class="chapter" data-level="5.6.2" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#combining-filtering-criteria"><i class="fa fa-check"></i><b>5.6.2</b> Combining Filtering Criteria</a></li>
<li class="chapter" data-level="5.6.3" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#removing-by-ceriteria"><i class="fa fa-check"></i><b>5.6.3</b> Removing by Ceriteria</a></li>
<li class="chapter" data-level="5.6.4" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#handling-nas"><i class="fa fa-check"></i><b>5.6.4</b> Handling NAs</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#arranging-data"><i class="fa fa-check"></i><b>5.7</b> Arranging Data</a></li>
<li class="chapter" data-level="5.8" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#summarising-data"><i class="fa fa-check"></i><b>5.8</b> Summarising Data</a></li>
<li class="chapter" data-level="5.9" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#grouping-data"><i class="fa fa-check"></i><b>5.9</b> Grouping Data</a><ul>
<li class="chapter" data-level="5.9.1" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#ungrouping-data"><i class="fa fa-check"></i><b>5.9.1</b> Ungrouping Data</a></li>
</ul></li>
<li class="chapter" data-level="5.10" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#chaining-many-functions"><i class="fa fa-check"></i><b>5.10</b> Chaining Many Functions</a></li>
<li class="chapter" data-level="5.11" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#saving-data"><i class="fa fa-check"></i><b>5.11</b> Saving Data</a><ul>
<li class="chapter" data-level="5.11.1" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#csv-files"><i class="fa fa-check"></i><b>5.11.1</b> CSV Files</a></li>
<li class="chapter" data-level="5.11.2" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#r-data-files"><i class="fa fa-check"></i><b>5.11.2</b> R Data Files</a></li>
</ul></li>
<li class="chapter" data-level="5.12" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#exercises-4"><i class="fa fa-check"></i><b>5.12</b> Exercises</a><ul>
<li class="chapter" data-level="5.12.1" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#question-1-4"><i class="fa fa-check"></i><b>5.12.1</b> Question 1</a></li>
<li class="chapter" data-level="5.12.2" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#question-2-4"><i class="fa fa-check"></i><b>5.12.2</b> Question 2</a></li>
<li class="chapter" data-level="5.12.3" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#question-3-4"><i class="fa fa-check"></i><b>5.12.3</b> Question 3</a></li>
<li class="chapter" data-level="5.12.4" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#question-4-4"><i class="fa fa-check"></i><b>5.12.4</b> Question 4</a></li>
<li class="chapter" data-level="5.12.5" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#question-5-4"><i class="fa fa-check"></i><b>5.12.5</b> Question 5</a></li>
<li class="chapter" data-level="5.12.6" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#question-6-4"><i class="fa fa-check"></i><b>5.12.6</b> Question 6</a></li>
<li class="chapter" data-level="5.12.7" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#question-7-4"><i class="fa fa-check"></i><b>5.12.7</b> Question 7</a></li>
<li class="chapter" data-level="5.12.8" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#question-8-4"><i class="fa fa-check"></i><b>5.12.8</b> Question 8</a></li>
<li class="chapter" data-level="5.12.9" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#question-9-4"><i class="fa fa-check"></i><b>5.12.9</b> Question 9</a></li>
<li class="chapter" data-level="5.12.10" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#question-10-3"><i class="fa fa-check"></i><b>5.12.10</b> Question 10</a></li>
<li class="chapter" data-level="5.12.11" data-path="data-manipulation-2.html"><a href="data-manipulation-2.html#question-11-1"><i class="fa fa-check"></i><b>5.12.11</b> Question 11</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html"><i class="fa fa-check"></i><b>6</b> Simple Statistical Tests</a><ul>
<li class="chapter" data-level="6.1" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#getting-started-3"><i class="fa fa-check"></i><b>6.1</b> Getting Started</a></li>
<li class="chapter" data-level="6.2" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#correlation"><i class="fa fa-check"></i><b>6.2</b> Correlation</a><ul>
<li class="chapter" data-level="6.2.1" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#analysing-real-data"><i class="fa fa-check"></i><b>6.2.1</b> Analysing Real Data</a></li>
<li class="chapter" data-level="6.2.2" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#checking-assumptions"><i class="fa fa-check"></i><b>6.2.2</b> Checking Assumptions</a></li>
<li class="chapter" data-level="6.2.3" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#running-a-correlation"><i class="fa fa-check"></i><b>6.2.3</b> Running a Correlation</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#t-tests"><i class="fa fa-check"></i><b>6.3</b> <em>t</em>-tests</a><ul>
<li class="chapter" data-level="6.3.1" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#one-sample-t-tests"><i class="fa fa-check"></i><b>6.3.1</b> One-Sample <em>t</em>-tests</a></li>
<li class="chapter" data-level="6.3.2" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#independent-samples-t-tests"><i class="fa fa-check"></i><b>6.3.2</b> Independent-Samples <em>t</em>-tests</a></li>
<li class="chapter" data-level="6.3.3" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#paired-samples-t-tests"><i class="fa fa-check"></i><b>6.3.3</b> Paired-Samples <em>t</em>-tests</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#anova"><i class="fa fa-check"></i><b>6.4</b> ANOVA</a><ul>
<li class="chapter" data-level="6.4.1" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#one-way-anova"><i class="fa fa-check"></i><b>6.4.1</b> One-Way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#linear-regression"><i class="fa fa-check"></i><b>6.5</b> Linear Regression</a><ul>
<li class="chapter" data-level="6.5.1" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#general-linear-model"><i class="fa fa-check"></i><b>6.5.1</b> General Linear Model</a></li>
<li class="chapter" data-level="6.5.2" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#generalised-linear-model"><i class="fa fa-check"></i><b>6.5.2</b> Generalised Linear Model</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#exercises-5"><i class="fa fa-check"></i><b>6.6</b> Exercises</a><ul>
<li class="chapter" data-level="6.6.1" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#question-1-5"><i class="fa fa-check"></i><b>6.6.1</b> Question 1</a></li>
<li class="chapter" data-level="6.6.2" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#question-2-5"><i class="fa fa-check"></i><b>6.6.2</b> Question 2</a></li>
<li class="chapter" data-level="6.6.3" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#question-3-5"><i class="fa fa-check"></i><b>6.6.3</b> Question 3</a></li>
<li class="chapter" data-level="6.6.4" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#question-4-5"><i class="fa fa-check"></i><b>6.6.4</b> Question 4</a></li>
<li class="chapter" data-level="6.6.5" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#question-5-5"><i class="fa fa-check"></i><b>6.6.5</b> Question 5</a></li>
<li class="chapter" data-level="6.6.6" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#question-6-5"><i class="fa fa-check"></i><b>6.6.6</b> Question 6</a></li>
<li class="chapter" data-level="6.6.7" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#question-7-5"><i class="fa fa-check"></i><b>6.6.7</b> Question 7</a></li>
<li class="chapter" data-level="6.6.8" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#question-8-5"><i class="fa fa-check"></i><b>6.6.8</b> Question 8</a></li>
<li class="chapter" data-level="6.6.9" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#question-9-5"><i class="fa fa-check"></i><b>6.6.9</b> Question 9</a></li>
<li class="chapter" data-level="6.6.10" data-path="simple-statistical-tests.html"><a href="simple-statistical-tests.html#question-10-4"><i class="fa fa-check"></i><b>6.6.10</b> Question 10</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html"><i class="fa fa-check"></i><b>7</b> Advanced Statistical Tests</a><ul>
<li class="chapter" data-level="7.1" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html#getting-started-4"><i class="fa fa-check"></i><b>7.1</b> Getting Started</a></li>
<li class="chapter" data-level="7.2" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html#multilevel-analyses"><i class="fa fa-check"></i><b>7.2</b> Multilevel Analyses</a><ul>
<li class="chapter" data-level="7.2.1" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html#preparation-of-data"><i class="fa fa-check"></i><b>7.2.1</b> Preparation of Data</a></li>
<li class="chapter" data-level="7.2.2" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html#multilevel-regression"><i class="fa fa-check"></i><b>7.2.2</b> Multilevel Regression</a></li>
<li class="chapter" data-level="7.2.3" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html#multilevel-anova"><i class="fa fa-check"></i><b>7.2.3</b> Multilevel ANOVA</a></li>
<li class="chapter" data-level="7.2.4" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html#multiple-contrasts"><i class="fa fa-check"></i><b>7.2.4</b> Multiple Contrasts</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html#multifactorial-analyses"><i class="fa fa-check"></i><b>7.3</b> Multifactorial Analyses</a><ul>
<li class="chapter" data-level="7.3.1" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html#multifactorial-anova"><i class="fa fa-check"></i><b>7.3.1</b> Multifactorial ANOVA</a></li>
<li class="chapter" data-level="7.3.2" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html#multiple-regression"><i class="fa fa-check"></i><b>7.3.2</b> Multiple Regression</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html#mixed-analyses"><i class="fa fa-check"></i><b>7.4</b> Mixed Analyses</a><ul>
<li class="chapter" data-level="7.4.1" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html#mixed-linear-models"><i class="fa fa-check"></i><b>7.4.1</b> Mixed Linear Models</a></li>
<li class="chapter" data-level="7.4.2" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html#mixed-anova"><i class="fa fa-check"></i><b>7.4.2</b> Mixed ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html#a-note-on-sum-of-squares"><i class="fa fa-check"></i><b>7.5</b> A Note on Sum of Squares</a></li>
<li class="chapter" data-level="7.6" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html#exercises-6"><i class="fa fa-check"></i><b>7.6</b> Exercises</a><ul>
<li class="chapter" data-level="7.6.1" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html#question-1-6"><i class="fa fa-check"></i><b>7.6.1</b> Question 1</a></li>
<li class="chapter" data-level="7.6.2" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html#question-2-6"><i class="fa fa-check"></i><b>7.6.2</b> Question 2</a></li>
<li class="chapter" data-level="7.6.3" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html#question-3-6"><i class="fa fa-check"></i><b>7.6.3</b> Question 3</a></li>
<li class="chapter" data-level="7.6.4" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html#question-4-6"><i class="fa fa-check"></i><b>7.6.4</b> Question 4</a></li>
<li class="chapter" data-level="7.6.5" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html#question-5-6"><i class="fa fa-check"></i><b>7.6.5</b> Question 5</a></li>
<li class="chapter" data-level="7.6.6" data-path="advanced-statistical-tests.html"><a href="advanced-statistical-tests.html#question-6-6"><i class="fa fa-check"></i><b>7.6.6</b> Question 6</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html"><i class="fa fa-check"></i><b>8</b> Simulation and Calculating Power</a><ul>
<li class="chapter" data-level="8.1" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#getting-started-5"><i class="fa fa-check"></i><b>8.1</b> Getting Started</a></li>
<li class="chapter" data-level="8.2" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#simulating-data"><i class="fa fa-check"></i><b>8.2</b> Simulating Data</a><ul>
<li class="chapter" data-level="8.2.1" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#the-uniform-distribution"><i class="fa fa-check"></i><b>8.2.1</b> The Uniform Distribution</a></li>
<li class="chapter" data-level="8.2.2" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#the-normal-distribution"><i class="fa fa-check"></i><b>8.2.2</b> The Normal Distribution</a></li>
<li class="chapter" data-level="8.2.3" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#the-binomial-distribution"><i class="fa fa-check"></i><b>8.2.3</b> The Binomial Distribution</a></li>
<li class="chapter" data-level="8.2.4" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#flexible-sampling"><i class="fa fa-check"></i><b>8.2.4</b> Flexible Sampling</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#sampling-for-inference"><i class="fa fa-check"></i><b>8.3</b> Sampling for Inference</a><ul>
<li class="chapter" data-level="8.3.1" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#understanding-p-values-and-type-i-errors"><i class="fa fa-check"></i><b>8.3.1</b> Understanding p-values and Type-I Errors</a></li>
<li class="chapter" data-level="8.3.2" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#understanding-power-and-type-ii-errors"><i class="fa fa-check"></i><b>8.3.2</b> Understanding Power and Type-II Errors</a></li>
<li class="chapter" data-level="8.3.3" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#flexible-power-analyses-with-simulation"><i class="fa fa-check"></i><b>8.3.3</b> Flexible Power Analyses with Simulation</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#performing-power-analyses-from-packages"><i class="fa fa-check"></i><b>8.4</b> Performing Power Analyses from Packages</a></li>
<li class="chapter" data-level="8.5" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#exercises-7"><i class="fa fa-check"></i><b>8.5</b> Exercises</a><ul>
<li class="chapter" data-level="8.5.1" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#introduction-and-setup-1"><i class="fa fa-check"></i><b>8.5.1</b> Introduction and Setup</a></li>
<li class="chapter" data-level="8.5.2" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#question-1-7"><i class="fa fa-check"></i><b>8.5.2</b> Question 1</a></li>
<li class="chapter" data-level="8.5.3" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#question-2-7"><i class="fa fa-check"></i><b>8.5.3</b> Question 2</a></li>
<li class="chapter" data-level="8.5.4" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#question-3-7"><i class="fa fa-check"></i><b>8.5.4</b> Question 3</a></li>
<li class="chapter" data-level="8.5.5" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#question-4-7"><i class="fa fa-check"></i><b>8.5.5</b> Question 4</a></li>
<li class="chapter" data-level="8.5.6" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#question-5-7"><i class="fa fa-check"></i><b>8.5.6</b> Question 5</a></li>
<li class="chapter" data-level="8.5.7" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#question-6-7"><i class="fa fa-check"></i><b>8.5.7</b> Question 6</a></li>
<li class="chapter" data-level="8.5.8" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#question-7-6"><i class="fa fa-check"></i><b>8.5.8</b> Question 7</a></li>
<li class="chapter" data-level="8.5.9" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#question-8-6"><i class="fa fa-check"></i><b>8.5.9</b> Question 8</a></li>
<li class="chapter" data-level="8.5.10" data-path="simulation-and-calculating-power.html"><a href="simulation-and-calculating-power.html#question-9-6"><i class="fa fa-check"></i><b>8.5.10</b> Question 9</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="mixed-effects-models.html"><a href="mixed-effects-models.html"><i class="fa fa-check"></i><b>9</b> Mixed Effects Models</a></li>
<li class="chapter" data-level="10" data-path="creating-reproducible-documents.html"><a href="creating-reproducible-documents.html"><i class="fa fa-check"></i><b>10</b> Creating Reproducible Documents</a><ul>
<li class="chapter" data-level="10.1" data-path="creating-reproducible-documents.html"><a href="creating-reproducible-documents.html#the-final-lesson"><i class="fa fa-check"></i><b>10.1</b> The Final Lesson</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R for Psych</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="simulation-and-calculating-power" class="section level1">
<h1><span class="header-section-number">Chapter 8</span> Simulation and Calculating Power</h1>
<p>In this session we’ll cover how to simualte data to improve our statistical inferences. We’ll use simulation to perform power analyses, and to understand more about how <em>p</em>-values work. Finally, we’ll look at how you can calculate power easily and quickly in several pre-existing packages and functions in R.</p>
<p>Specifically, we’ll cover:</p>
<ul>
<li>simulating data in R</li>
<li>simulation-based power analyses</li>
<li>packages for power analysis</li>
</ul>
<div id="getting-started-5" class="section level2">
<h2><span class="header-section-number">8.1</span> Getting Started</h2>
<p>As always, we first need to load the <code>tidyverse</code> set of packages for this Chapter.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># load packages</span>
<span class="kw">library</span>(tidyverse)</code></pre></div>
</div>
<div id="simulating-data" class="section level2">
<h2><span class="header-section-number">8.2</span> Simulating Data</h2>
<p>First off, we’ll explore different ways to simulate data using some of the basic functions in R. We’ll look at randomly sampling data that adheres to the following distributions:</p>
<ul>
<li>Uniform, using <code>runif()</code> (read: <strong>r</strong>andom <strong>unif</strong>orm)</li>
<li>Normal, using <code>rnorm()</code> (read: <strong>r</strong>andom <strong>norm</strong>al )</li>
<li>Binomial, using <code>rbinom()</code> (read: <strong>r</strong>andom <strong>binom</strong>ial)</li>
</ul>
<p>Additionally, we’ll look at randomly sampling data with and without replacement, and how we can determine bias in our sampling procedure by defining the probability with which items should be sampled.</p>
<p>We’ll look at sampling data following these distributions as this provides us with a better understanding of our data, and equips us with the means to evaluate our research plans prior to the expensive (in terms of time and money) procedure of testing. Put simply, simulating data is useful because it allows us to do things like calculate power for simple and complex experimental designs, and to observe when participants are performing to change in tasks.</p>
<div id="the-uniform-distribution" class="section level3">
<h3><span class="header-section-number">8.2.1</span> The Uniform Distribution</h3>
<p>With the uniform distribution, we sample numbers such that all values are equally likely to be drawn from our range. Try this out a few times:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">runif</span>(<span class="dt">n =</span> <span class="dv">5</span>, <span class="dt">min =</span> <span class="dv">1</span>, <span class="dt">max =</span> <span class="dv">10</span>)</code></pre></div>
<pre><code>## [1] 3.300586 2.342055 4.873663 9.191708 5.319560</code></pre>
<p>In all likelihood, you should get different numbers to those above, but your numbers will all be between 1 and 10 (excluding these two values). You can increase the amount of numbers sampled by changing <code>n</code> to anything else. For example, try this:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">runif</span>(<span class="dt">n =</span> <span class="dv">10</span>, <span class="dt">min =</span> <span class="dv">1</span>, <span class="dt">max =</span> <span class="dv">10</span>)</code></pre></div>
<pre><code>##  [1] 8.011183 5.748096 1.380451 7.302121 5.467758 6.987622 2.161111
##  [8] 5.345088 5.670862 4.214587</code></pre>
<p>Now we have 10 numbers between 1 and 10.</p>
<p>Finally, we can change the minimum and maximum values, or the range of values we want to sample from. Let’s sample 10 numbers from between 0 and 1.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">runif</span>(<span class="dt">n =</span> <span class="dv">10</span>, <span class="dt">min =</span> <span class="dv">0</span>, <span class="dt">max =</span> <span class="dv">1</span>)</code></pre></div>
<pre><code>##  [1] 0.90863606 0.60394266 0.78368223 0.47517589 0.03186038 0.51023136
##  [7] 0.51073424 0.58464829 0.76034355 0.08140943</code></pre>
<p>What happens if we calculate the mean from 10 samples from a uniform distribution? What about 100, 1000, or even 10000?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">runif</span>(<span class="dt">n =</span> <span class="dv">10</span>, <span class="dt">min =</span> <span class="dv">0</span>, <span class="dt">max =</span> <span class="dv">1</span>) %&gt;%<span class="st"> </span><span class="kw">mean</span>()</code></pre></div>
<pre><code>## [1] 0.4962173</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">runif</span>(<span class="dt">n =</span> <span class="dv">100</span>, <span class="dt">min =</span> <span class="dv">0</span>, <span class="dt">max =</span> <span class="dv">1</span>) %&gt;%<span class="st"> </span><span class="kw">mean</span>()</code></pre></div>
<pre><code>## [1] 0.4754119</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">runif</span>(<span class="dt">n =</span> <span class="dv">1000</span>, <span class="dt">min =</span> <span class="dv">0</span>, <span class="dt">max =</span> <span class="dv">1</span>) %&gt;%<span class="st"> </span><span class="kw">mean</span>()</code></pre></div>
<pre><code>## [1] 0.4878579</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">runif</span>(<span class="dt">n =</span> <span class="dv">10000</span>, <span class="dt">min =</span> <span class="dv">0</span>, <span class="dt">max =</span> <span class="dv">1</span>) %&gt;%<span class="st"> </span><span class="kw">mean</span>()</code></pre></div>
<pre><code>## [1] 0.5000408</code></pre>
<p>As you can see, as we draw more samples, the mean of these samples better represents the true distribution of our sampling procedure. Think about how this could impact your studies. With small sample sizes, we’re likely to get skewed data that tends towards the extremes.</p>
</div>
<div id="the-normal-distribution" class="section level3">
<h3><span class="header-section-number">8.2.2</span> The Normal Distribution</h3>
<p>Alternatively, we can sample continuous data from the normal distribution. We might use this to generate data on a continuous scale with a normal distribution in the population, such as the height and weight of a participant, or even their IQ.</p>
<p>To do this, we use the <code>rnorm()</code> function. You may have noticed me doing this when creating data for the previous sessions, and that’s with good reason; we often fit our data with models that assume a normal distribution of our variables, and so creating data with this assumed distribution often meets the assumptions of the tests we’d like to run.</p>
<p>This sampling function provides us with a good range of values if we know (or can guess at) the mean and standard deviation of a sample from a population. Let’s see how this works. Below, we’ll sample some data from a population where we know the mean and standard deviation; the IQ test. Here, the mean is 100 and the standard deviation is 15. Let’s go ahead and sample 10 people from this population.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">10</span>, <span class="dt">mean =</span> <span class="dv">100</span>, <span class="dt">sd =</span> <span class="dv">15</span>)</code></pre></div>
<pre><code>##  [1]  82.16277  99.75992 128.28859  76.65559  73.06495  97.49910  96.44725
##  [8] 102.10636  91.52518 125.11196</code></pre>
<p>OK, we have a good range of values for our IQ test here, but as before, with a small sample size our distribution will be skewed. Let’s observe how this plays out with a density plot. (Here, I’m being lazy and not defining <code>mapping = aes()</code>, as ggplot understands that what we put in <code>aes()</code> will be mapped to the data/plot.)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">5</span>)
small_samp &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">100</span>, <span class="dt">mean =</span> <span class="dv">100</span>, <span class="dt">sd =</span> <span class="dv">15</span>)
large_samp &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">1000</span>, <span class="dt">mean =</span> <span class="dv">100</span>, <span class="dt">sd =</span> <span class="dv">15</span>)

<span class="kw">ggplot</span>() +<span class="st"> </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(small_samp)) +<span class="st"> </span><span class="kw">coord_cartesian</span>(<span class="dt">x =</span> <span class="kw">c</span>(<span class="dv">50</span>, <span class="dv">150</span>))</code></pre></div>
<p><img src="R_for_Psych_files/figure-html/8_norm_sample_sizes-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>() +<span class="st"> </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(large_samp)) +<span class="st"> </span><span class="kw">coord_cartesian</span>(<span class="dt">x =</span> <span class="kw">c</span>(<span class="dv">50</span>, <span class="dv">150</span>))</code></pre></div>
<p><img src="R_for_Psych_files/figure-html/8_norm_sample_sizes-2.png" width="672" /></p>
<p>As before, the data seem to fit the population distribution better when we have larger sample sizes. Let’s change the standard deviation to see how variance in our samples influences the distribution of effects. Here, we’ll just focus on the larger sample size:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">5</span>)
large_sd_samp &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">1000</span>, <span class="dt">mean =</span> <span class="dv">100</span>, <span class="dt">sd =</span> <span class="dv">15</span>)
small_sd_samp &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> <span class="dv">1000</span>, <span class="dt">mean =</span> <span class="dv">100</span>, <span class="dt">sd =</span> <span class="fl">1.5</span>)

<span class="kw">ggplot</span>() +<span class="st"> </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(large_sd_samp)) +<span class="st"> </span><span class="kw">coord_cartesian</span>(<span class="dt">x =</span> <span class="kw">c</span>(<span class="dv">50</span>, <span class="dv">150</span>))</code></pre></div>
<p><img src="R_for_Psych_files/figure-html/8_norm_standard_deviation-1.png" width="672" /></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>() +<span class="st"> </span><span class="kw">geom_density</span>(<span class="kw">aes</span>(small_sd_samp)) +<span class="st"> </span><span class="kw">coord_cartesian</span>(<span class="dt">x =</span> <span class="kw">c</span>(<span class="dv">50</span>, <span class="dv">150</span>))</code></pre></div>
<p><img src="R_for_Psych_files/figure-html/8_norm_standard_deviation-2.png" width="672" /></p>
<p>As you can see, as we sample from a population with a smaller standard deviation, our samples will be closer to the mean score. This has important implications for our statistical tests; the larger the standard deviation within our samples, the more samples we’ll need to detect an effect.</p>
</div>
<div id="the-binomial-distribution" class="section level3">
<h3><span class="header-section-number">8.2.3</span> The Binomial Distribution</h3>
<p>Next, we’ll look at sampling from a binomial distribution. We might use this to generate data on a binomial scale, such as the probability of a success/failure in a task (e.g. did they get the question right or not?). We sample from a binomial distribution using the <code>rbinom()</code> function.</p>
<p>This function takes 3 arguments: <code>n</code>, the number of observations we’d like to see; <code>size</code>, the number of trials within an observation; and <code>prob</code> the probability of a success (1) (vs. failure, 0) on each trial.</p>
<p>Below, we’ll get 10 observations, of 1 trial each, with a success rate of 50% on each trial.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1000</span>)
<span class="kw">rbinom</span>(<span class="dt">n =</span> <span class="dv">10</span>, <span class="dt">size =</span> <span class="dv">1</span>, <span class="dt">prob =</span> <span class="fl">0.5</span>)</code></pre></div>
<pre><code>##  [1] 0 1 0 1 1 0 1 1 0 0</code></pre>
<p>As you can see, our sampling produced 5 successes (1) and 5 failures (0). What if we want to make each observation the number of successes in 20 trials. Let’s change the size argument to 20.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1000</span>)
<span class="kw">rbinom</span>(<span class="dt">n =</span> <span class="dv">10</span>, <span class="dt">size =</span> <span class="dv">20</span>, <span class="dt">prob =</span> <span class="fl">0.5</span>)</code></pre></div>
<pre><code>##  [1]  9 12  7 11 10  7 11 10  8  9</code></pre>
<p>Now each trial roughly follows a 50% success rate as before, but each observation is out of 20 trials. We can convert these to proportions by simply dividing the whole thing by the same value as our size argument.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1000</span>)
<span class="kw">rbinom</span>(<span class="dt">n =</span> <span class="dv">10</span>, <span class="dt">size =</span> <span class="dv">20</span>, <span class="dt">prob =</span> <span class="fl">0.5</span>) /<span class="st"> </span><span class="dv">20</span></code></pre></div>
<pre><code>##  [1] 0.45 0.60 0.35 0.55 0.50 0.35 0.55 0.50 0.40 0.45</code></pre>
<p>Did you notice the repetition of 20 in our code? We’ll save some repetition for the value of 20 by defining the number of trials in a separate object, and passing the name of this object to our argument. This should get you used to using objects as holders for values as a precursor to writing your own functions!</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># define number of trials</span>
n_trials &lt;-<span class="st"> </span><span class="dv">20</span>

<span class="kw">set.seed</span>(<span class="dv">1000</span>)
<span class="kw">rbinom</span>(<span class="dt">n =</span> <span class="dv">10</span>, <span class="dt">size =</span> n_trials, <span class="dt">prob =</span> <span class="fl">0.5</span>) /<span class="st"> </span>n_trials</code></pre></div>
<pre><code>##  [1] 0.45 0.60 0.35 0.55 0.50 0.35 0.55 0.50 0.40 0.45</code></pre>
<p>Also, I think our code is a bit more readable now that we know what the 20 represents!</p>
<p>Can you guess what the mean of a 1000 samples might look like? What about the distribution of these? Try calculating the mean of 1000 samples of 20 trials with a probability of 0.5 and plot this out using a histrogram.</p>
</div>
<div id="flexible-sampling" class="section level3">
<h3><span class="header-section-number">8.2.4</span> Flexible Sampling</h3>
<p>Finally, we can also randomly sample discrete variables with pre-defined probabilities. Nicely, we can use the same function to do this for strings of character or for integers. To do this, we use the <code>sample()</code> function. This is useful for creating dummy data sets where we might want to randomly sample names for participants, or outcomes with a bias on our draws.</p>
<p>We can simply define what to sample from with the <code>x</code> argument. If this is an integer, R will sample from any positive integer up to and including this limit. As before we can ask for any number of samples with the <code>size</code> argument.</p>
<p>Finally, we can specify if we want to replace these numbers with the <code>replace</code> argument. If we set this to true, R puts any drawn numbers back in the bag before picking them out again. If we set this to FALSE, R will not put the numbers back in the bag before drawing again, so we can’t redraw the same number.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1000</span>)
<span class="kw">sample</span>(<span class="dt">x =</span> <span class="dv">10</span>, <span class="dt">size =</span> <span class="dv">10</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>##  [1] 4 8 2 7 6 1 8 6 3 3</code></pre>
<p>Did you notice how we got 3 twice? Let’s change the <code>replace</code> argument to <code>FALSE</code> to see what happens.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1000</span>)
<span class="kw">sample</span>(<span class="dt">x =</span> <span class="dv">10</span>, <span class="dt">size =</span> <span class="dv">10</span>, <span class="dt">replace =</span> <span class="ot">FALSE</span>)</code></pre></div>
<pre><code>##  [1]  4  7  1  5 10  8  3  2  9  6</code></pre>
<p>Now we only get unique numbers. If we ask to draw more numbers than we have unique values, this will fail.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1000</span>)
<span class="kw">sample</span>(<span class="dt">x =</span> <span class="dv">10</span>, <span class="dt">size =</span> <span class="dv">11</span>, <span class="dt">replace =</span> <span class="ot">FALSE</span>)</code></pre></div>
<p>We can also sample from characters, such as when we might want to create some data for the names of participants.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1000</span>)
names &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Glenn&quot;</span>, <span class="st">&quot;Nik&quot;</span>, <span class="st">&quot;Vera&quot;</span>, <span class="st">&quot;Neil&quot;</span>)
<span class="kw">sample</span>(<span class="dt">x =</span> names, <span class="dt">size =</span> <span class="dv">2</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## [1] &quot;Nik&quot;  &quot;Neil&quot;</code></pre>
<p>We can also set some pre-defined probabilities for the things we’ll sample from. Let’s say the probability of selecting “Glenn” is most likely in 10 draws.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">1000</span>)
names &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Glenn&quot;</span>, <span class="st">&quot;Nik&quot;</span>, <span class="st">&quot;Vera&quot;</span>, <span class="st">&quot;Neil&quot;</span>)
<span class="kw">sample</span>(<span class="dt">x =</span> names, <span class="dt">size =</span> <span class="dv">10</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>, <span class="dt">prob =</span> <span class="kw">c</span>(<span class="fl">0.7</span>, <span class="fl">0.1</span>, <span class="fl">0.1</span>, <span class="fl">0.1</span>))</code></pre></div>
<pre><code>##  [1] &quot;Glenn&quot; &quot;Vera&quot;  &quot;Glenn&quot; &quot;Glenn&quot; &quot;Glenn&quot; &quot;Glenn&quot; &quot;Vera&quot;  &quot;Glenn&quot;
##  [9] &quot;Glenn&quot; &quot;Glenn&quot;</code></pre>
<p>As you can see, Glenn gets drawn most often because this has the highest probability to be drawn (i.e. the first thing in <code>x</code> is related to the first probability in <code>prob</code>).</p>
<p>This sampling procedure is very flexible for simulating data if we have some idea about the probabilities for things to be sampled. Let’s look at an example where sampling like this is useful.</p>
</div>
</div>
<div id="sampling-for-inference" class="section level2">
<h2><span class="header-section-number">8.3</span> Sampling for Inference</h2>
<p>Imagine we’re studying a person who claims to be a psychic. We decide to test their claim by getting them to take part in an experiment. In this experiment, we have 10 cards each with 1 of 5 symbols on the back. The psychic says that they can guess, above chance, which symbol is on the back of the card.</p>
<p>Let’s simulate their data for 10 attempts.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># sample the true values of the cards</span>
<span class="kw">set.seed</span>(<span class="dv">13</span>)
psychic_outcome &lt;-<span class="st"> </span><span class="kw">rbinom</span>(<span class="dt">n =</span> <span class="dv">1</span>, <span class="dt">size =</span> <span class="dv">10</span>, <span class="dt">prob =</span> <span class="fl">0.2</span>)

<span class="co"># see the true values</span>
psychic_outcome</code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>The psychic guessed 3 cards correctly out of 10. However, we know that on each trial, the probability of a success is only 20% (i.e. 1 in 5). Was the psychic telling the truth, or should we have reason to doubt their claim?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">binom.test</span>(<span class="dt">x =</span> psychic_outcome, <span class="dt">n =</span> <span class="dv">10</span>, <span class="dt">p =</span> <span class="fl">0.2</span>)</code></pre></div>
<pre><code>## 
##  Exact binomial test
## 
## data:  psychic_outcome and 10
## number of successes = 3, number of trials = 10, p-value = 0.4296
## alternative hypothesis: true probability of success is not equal to 0.2
## 95 percent confidence interval:
##  0.06673951 0.65245285
## sample estimates:
## probability of success 
##                    0.3</code></pre>
<p>So, it seems that although they performed above chance, the sample size is too small to consider this difference between the observed and expected probability of success to be meaningful.</p>
<p>What if we change it so the psychic got it right 30 times in 100 chances? We’ll simply multiply the number of successes and observations by 10 and test for a significant difference between the observed and expected probability.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">binom.test</span>(<span class="dt">x =</span> psychic_outcome *<span class="st"> </span><span class="dv">10</span>, <span class="dt">n =</span> <span class="dv">10</span> *<span class="st"> </span><span class="dv">10</span>, <span class="dt">p =</span> <span class="fl">0.2</span>)</code></pre></div>
<pre><code>## 
##  Exact binomial test
## 
## data:  psychic_outcome * 10 and 10 * 10
## number of successes = 30, number of trials = 100, p-value =
## 0.01695
## alternative hypothesis: true probability of success is not equal to 0.2
## 95 percent confidence interval:
##  0.2124064 0.3998147
## sample estimates:
## probability of success 
##                    0.3</code></pre>
<p>Now we have a significant effect showing indicating that we should reject the null hypothesis. But do any of you really believe that the psychic is truly psychic? Remember that we used the binomial sampling procedure to come up with these scores in the first place, so we know that the true probability of a success on each trial is 0.2, or 20%, which is chance.</p>
<p>Let’s change our sampling procedure into a function so we can better explore whether or not we should trust the outcome of this one study. Before we do so, we’ll see how functions work, and why they are useful in our work.</p>
<div id="understanding-p-values-and-type-i-errors" class="section level3">
<h3><span class="header-section-number">8.3.1</span> Understanding p-values and Type-I Errors</h3>
<p>User defined functions in R take the form of:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">function_name &lt;-<span class="st"> </span>function(parameters_to_vary) {
  things_for_the_function_to_do
}</code></pre></div>
<p>We first have to specify a name for our function. Often, it’s best to use verb-like naming here, as your functions are things you want to do to something (e.g. calculate descriptive statitics etc.). You then assign to this name how the function works. Within the function call in parentheses, you can define different parameters of your function that you’d like to vary. This simply makes your function flexible to doing things to data with different inputs. Finally, within the body of the function, <code>{here is the body}</code>, we define things to do to your parameters that are passed to the function. The last thing that you type in your function is what your function returns to you when you run it (i.e. what you will see when you run the function).</p>
<p>Let’s transform our sampling and testing procedure into a function. I’ve commented this code so you understand how it works.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># define function name and parameters to vary</span>
simulate_psychic_test &lt;-<span class="st"> </span>function(n_trials, prob_success) {
  
  <span class="co"># sample binomial data (successs or not) for varying trials and probabilities </span>
  psychic_outcome &lt;-<span class="st"> </span><span class="kw">rbinom</span>(<span class="dt">n =</span> <span class="dv">1</span>, <span class="dt">size =</span> n_trials, <span class="dt">prob =</span> prob_success)
  
  <span class="co"># run a binomial test on the sampled data against your proability</span>
  test &lt;-<span class="st"> </span><span class="kw">binom.test</span>(<span class="dt">x =</span> psychic_outcome, <span class="dt">n =</span> n_trials, <span class="dt">p =</span> prob_success)
  
  <span class="co"># retrieve the p-value, this is what is returned in our function</span>
  test$p.value
}</code></pre></div>
<p>Congratulations, you’ve just made your first user-defined function in R! Here, we’ve defined a function that will take a number of trials and a probability of success on each trial. It will then sample some data under those parameters, before testing it against the probability of success. Finally, it will extract the <em>p</em>-value from that test and return it to you. Let’s see this in action.</p>
<p>Run and rerun the code below several times to see what happens. What do the <em>p</em>-values look like? Remember, a value below 0.05 is typical in psychology for the cut-off point where we’ll reject the null hypothesis of no difference between the observed and predicted probabilities of success.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">simulate_psychic_test</span>(<span class="dt">n_trials =</span> <span class="dv">100</span>, <span class="dt">prob_success =</span> <span class="fl">0.2</span>)</code></pre></div>
<pre><code>## [1] 0.5322562</code></pre>
<p>Ok, so you’ve seen how these <em>p</em>-values shift even when we know there’s no true effect. Let’s simulate the experiment 100 times to see what happens to the distribution of the <em>p</em>-values.</p>
<p>Nicely, R has a <code>replicate()</code> function, which replicates whatever we ask it to do by a pre-defined number. This replicate function takes <code>n</code> as an argument, which is the number of replication to carry out, plus whatever you want to replicate.</p>
<p>Can you predict what will happen?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">simulations &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dt">n =</span> <span class="dv">100</span>, 
                         <span class="kw">simulate_psychic_test</span>(<span class="dt">n_trials =</span> <span class="dv">100</span>, 
                                               <span class="dt">prob_success =</span> <span class="fl">0.2</span>
                                               )
                         )</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>() +<span class="st"> </span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">mapping =</span> <span class="kw">aes</span>(simulations),
                 <span class="dt">binwidth =</span> <span class="fl">0.05</span>,
                 <span class="dt">boundary =</span> <span class="dv">0</span>,
                 <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>,
                 <span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>) +
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), 
                     <span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">0</span>, <span class="dt">to =</span> <span class="dv">1</span>, <span class="dt">by =</span> <span class="fl">0.05</span>)
                     ) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="fl">0.05</span>, <span class="dt">linetype =</span> <span class="dv">2</span>, <span class="dt">colour =</span> <span class="st">&quot;red&quot;</span>) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;p-value&quot;</span>) +
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">size=</span><span class="dv">8</span>))</code></pre></div>
<p><img src="R_for_Psych_files/figure-html/8_simulate_function_plot-1.png" width="672" /></p>
<p>The red cut-off line shows the number of values that fall below our 0.05 cut-off point for our <em>p</em>-values. That looks like roughly 3 in 100 samples, or 3% of our simulated studies.</p>
<p>Try increasing the number of replications for the experiment to see how the <em>p</em>-values change. How does it look with 10,000 simulated studies?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">simulations &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dt">n =</span> <span class="dv">10000</span>, 
                         <span class="kw">simulate_psychic_test</span>(<span class="dt">n_trials =</span> <span class="dv">100</span>, 
                                               <span class="dt">prob_success =</span> <span class="fl">0.2</span>
                                               )
                         )</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>() +<span class="st"> </span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(simulations),
                 <span class="dt">binwidth =</span> <span class="fl">0.05</span>,
                 <span class="dt">boundary =</span> <span class="dv">0</span>,
                 <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>,
                 <span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>) +
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), 
                     <span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">0</span>, <span class="dt">to =</span> <span class="dv">1</span>, <span class="dt">by =</span> <span class="fl">0.05</span>)
                     ) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="fl">0.05</span>, <span class="dt">linetype =</span> <span class="dv">2</span>, <span class="dt">colour =</span> <span class="st">&quot;red&quot;</span>) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;p-value&quot;</span>) +
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">size=</span><span class="dv">8</span>))</code></pre></div>
<p><img src="R_for_Psych_files/figure-html/8_simulate_function_replications_plot-1.png" width="672" /></p>
<p>Here we have roughly 500 studies showing <em>p</em>-values below 0.05. Thats 5% of the 10,000 studies. Is that surprising? Even when there’s no effect in the population, with repeated sampling we’re bound to find some cases where we have <em>p</em>-values below 0.05. That’s why replications are so important for our research!</p>
<p>This false-positive rate is the type-I error rate of our study, and is determined by our <em>p</em>-value. This determines the amount of time we will incorrectly reject the null hypothesis in the long run (i.e. if we run several studies over time).</p>
</div>
<div id="understanding-power-and-type-ii-errors" class="section level3">
<h3><span class="header-section-number">8.3.2</span> Understanding Power and Type-II Errors</h3>
<p>What if we change our function so that we can give the psychic a different probability to the true probability of a success?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># define function name and parameters to vary</span>
simulate_psychic_test &lt;-<span class="st"> </span>function(n_trials, prob_success, psychic_success) {
  
  <span class="co"># sample binomial data (successs or not) for varying trials and probabilities </span>
  psychic_outcome &lt;-<span class="st"> </span><span class="kw">rbinom</span>(<span class="dt">n =</span> <span class="dv">1</span>, <span class="dt">size =</span> n_trials, <span class="dt">prob =</span> psychic_success)
  
  <span class="co"># run a binomial test on the sampled data against your proability</span>
  test &lt;-<span class="st"> </span><span class="kw">binom.test</span>(<span class="dt">x =</span> psychic_outcome, <span class="dt">n =</span> n_trials, <span class="dt">p =</span> prob_success)
  
  <span class="co"># retrieve the p-value, this is what is returned in our function</span>
  test$p.value
}</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">true_effect_simulations &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dt">n =</span> <span class="dv">1000</span>, 
                         <span class="kw">simulate_psychic_test</span>(<span class="dt">n_trials =</span> <span class="dv">100</span>, 
                                               <span class="dt">prob_success =</span> <span class="fl">0.2</span>,
                                               <span class="dt">psychic_success =</span> <span class="fl">0.25</span>
                                               )
                         )</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>() +<span class="st"> </span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(true_effect_simulations),
                 <span class="dt">binwidth =</span> <span class="fl">0.05</span>,
                 <span class="dt">boundary =</span> <span class="dv">0</span>,
                 <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>,
                 <span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>) +
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), 
                     <span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">0</span>, <span class="dt">to =</span> <span class="dv">1</span>, <span class="dt">by =</span> <span class="fl">0.05</span>)
                     ) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="fl">0.05</span>, <span class="dt">linetype =</span> <span class="dv">2</span>, <span class="dt">colour =</span> <span class="st">&quot;red&quot;</span>) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;p-value&quot;</span>) +
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">size=</span><span class="dv">8</span>))</code></pre></div>
<p><img src="R_for_Psych_files/figure-html/8_function_type_II_plot-1.png" width="672" /></p>
<p>Now it looks like we have a much larger proportion of studies that give us <em>p</em>-values below 0.05. Actually, it’s 211, or 21.1%.</p>
<p>What does this tell us? Actually, this is the power of our study, or the probability for us to detect a true effect when it is present in the population. As such, 1-power is the type-II error rate, or the probability to reject the alternative hypothesis when a true effect is present in the population.</p>
<p>At only 21.1%, this is inadequate for our purposes. We generally aim for at least 80% in psychological research. Here we have a much larger chance of committing a type-II error, or incorrectly rejecting the alternative hypothesis when there is a true effect in the population.</p>
<p>We can use this simulating method to help determine the parameters of our study. Let’s look into increasing the sample size in our study, or the number of observations we make during the experiment.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">true_effect_simulations &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dt">n =</span> <span class="dv">1000</span>, 
                         <span class="kw">simulate_psychic_test</span>(<span class="dt">n_trials =</span> <span class="dv">600</span>, 
                                               <span class="dt">prob_success =</span> <span class="fl">0.2</span>,
                                               <span class="dt">psychic_success =</span> <span class="fl">0.25</span>
                                               )
                         )</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>() +<span class="st"> </span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="kw">aes</span>(true_effect_simulations),
                 <span class="dt">binwidth =</span> <span class="fl">0.05</span>,
                 <span class="dt">boundary =</span> <span class="dv">0</span>,
                 <span class="dt">fill =</span> <span class="st">&quot;white&quot;</span>,
                 <span class="dt">colour =</span> <span class="st">&quot;black&quot;</span>) +
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), 
                     <span class="dt">breaks =</span> <span class="kw">seq</span>(<span class="dt">from =</span> <span class="dv">0</span>, <span class="dt">to =</span> <span class="dv">1</span>, <span class="dt">by =</span> <span class="fl">0.05</span>)
                     ) +
<span class="st">  </span><span class="kw">geom_vline</span>(<span class="dt">xintercept =</span> <span class="fl">0.05</span>, <span class="dt">linetype =</span> <span class="dv">2</span>, <span class="dt">colour =</span> <span class="st">&quot;red&quot;</span>) +
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;p-value&quot;</span>) +
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">axis.text.x =</span> <span class="kw">element_text</span>(<span class="dt">size=</span><span class="dv">8</span>))</code></pre></div>
<p><img src="R_for_Psych_files/figure-html/8_do_function_type_II_power_plot-1.png" width="672" /></p>
<p>That looks better! Now, in most experiments, we’ll get a <em>p</em>-value below 0.05. How many studies detected this true effect? Our power for this study is:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">mean</span>(true_effect_simulations &lt;<span class="st"> </span><span class="fl">0.05</span>)</code></pre></div>
<pre><code>## [1] 0.821</code></pre>
<p>Great, at 600 trials we now have an 82.1% chance to detect a true effect if present. It looks like we’ll have one tired psychic by the end of this experiment!</p>
<p>As long as you can construct data that fits the form of your planned experiment you can use simulation to calculate the predicted power under the parameters that you set. <a href="https://youtu.be/avHLWnX2ehQ">As long as we have <em>t</em></a>- or <em>p</em>-values to capture, we can simulate data, fit our model, and count the number of <em>p</em>-values below our threshold (or <em>t</em>-values above our threshold) where we reject the null hypothesis in order to come up with the power of our study. Typically, around 1000 samples is enough for this.</p>
</div>
<div id="flexible-power-analyses-with-simulation" class="section level3">
<h3><span class="header-section-number">8.3.3</span> Flexible Power Analyses with Simulation</h3>
<div id="simulation-for-simple-designs" class="section level4">
<h4><span class="header-section-number">8.3.3.1</span> Simulation for Simple Designs</h4>
<p>Now we understand how we can use simulation to create data sets and observe the probability that we’ll detect a true effect with a simple design, we can build on our knowledge to look at more complex designs.</p>
<p>Let’s return to the IQ study data. Remember, that the IQ test has a mean of 100 and standard deviation of 15. Let’s run a power analysis to detect whether a predicted sample of people differ from this average range.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">calculate_IQ_power &lt;-<span class="st"> </span>function(n, sample_mean, sample_sd, pop_mean, pop_sd) {
  sample_data &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dt">n =</span> n, <span class="dt">mean =</span> sample_mean, <span class="dt">sd =</span> sample_sd)
  test &lt;-<span class="st"> </span><span class="kw">t.test</span>(sample_data, <span class="dt">mu =</span> pop_mean, <span class="dt">sd =</span> pop_sd)
  test$p.value
}</code></pre></div>
<p>Now let’s run our function, replicated 1000 times. We’ll sample assuming our population and sample have the same standard deviation, but the sample mean is 5 points higher than the general population. Finally, we’ll sample 60 people.</p>
<p>We’ll then calculate the mean number of <em>p</em>-values below our 0.05 cut off point to see our power.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p_vals &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">1000</span>, <span class="kw">calculate_IQ_power</span>(<span class="dv">60</span>, <span class="dv">105</span>, <span class="dv">15</span>, <span class="dv">100</span>, <span class="dv">15</span>))
<span class="kw">mean</span>(p_vals &lt;<span class="st"> </span><span class="fl">0.05</span>)</code></pre></div>
<pre><code>## [1] 0.735</code></pre>
<p>Great, 73.5% power is not bad at all. Maybe we should bump up the sample size a little to get to 80%.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p_vals &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">1000</span>, <span class="kw">calculate_IQ_power</span>(<span class="dv">75</span>, <span class="dv">105</span>, <span class="dv">15</span>, <span class="dv">100</span>, <span class="dv">15</span>))
<span class="kw">mean</span>(p_vals &lt;<span class="st"> </span><span class="fl">0.05</span>)</code></pre></div>
<pre><code>## [1] 0.835</code></pre>
<p>It looks like around 75 participants does a good job for us. What if the standard deviation for our sample was smaller? i.e. what if the samples tend to be more similar in their mean scores?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p_vals &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">1000</span>, <span class="kw">calculate_IQ_power</span>(<span class="dv">20</span>, <span class="dv">105</span>, <span class="fl">7.5</span>, <span class="dv">100</span>, <span class="dv">15</span>))
<span class="kw">mean</span>(p_vals &lt;<span class="st"> </span><span class="fl">0.05</span>)</code></pre></div>
<pre><code>## [1] 0.82</code></pre>
<p>Now it looks like we only need around 20 participants to achieve the same power.</p>
<p>What if the mean score is half as large as before?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">p_vals &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">1000</span>, <span class="kw">calculate_IQ_power</span>(<span class="dv">70</span>, <span class="fl">102.5</span>, <span class="fl">7.5</span>, <span class="dv">100</span>, <span class="dv">15</span>))
<span class="kw">mean</span>(p_vals &lt;<span class="st"> </span><span class="fl">0.05</span>)</code></pre></div>
<pre><code>## [1] 0.793</code></pre>
<p>Now we need more participants, even though the standard deviation is as small as before.</p>
<p>As you can see, sample size, effect sizes, and variance all affect the ability to detect a true effect.</p>
</div>
<div id="simulation-for-more-complex-designs" class="section level4">
<h4><span class="header-section-number">8.3.3.2</span> Simulation for More Complex Designs</h4>
<p>So far, we’ve looked at simulation for cases where we have a baseline condition to compare against. However, we often want to compare to or more groups against one another to determine if they differ on some outcome variable. For a <em>t</em>-test, this is as simple as sampling two sets of data using <code>rnorm()</code> and comparing the two against one another. However, we’ll look at a more complex 2 by 2 between-subjects design, which can be adapted to most scenarios.</p>
<p>Here, participants take part in 1 combination of 2 factors (A and B) each with 2 levels. To get started we first have to create a tibble to hold our simulated data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># how many subjects?</span>
n &lt;-<span class="st"> </span><span class="dv">60</span>

<span class="co"># create your design</span>
design &lt;-<span class="st"> </span><span class="kw">expand.grid</span>(<span class="dt">A =</span> <span class="kw">c</span>(-.<span class="dv">5</span>, .<span class="dv">5</span>), <span class="dt">B =</span> <span class="kw">c</span>(-.<span class="dv">5</span>, .<span class="dv">5</span>))

<span class="co"># create table of data</span>
data &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">subject =</span> <span class="dv">1</span>:<span class="st"> </span>n,
               <span class="dt">A =</span> <span class="kw">rep</span>(design$A, n/<span class="dv">4</span>),
               <span class="dt">B =</span> <span class="kw">rep</span>(design$B, n/<span class="dv">4</span>)
               )

<span class="co"># look at the data</span>
data</code></pre></div>
<pre><code>## # A tibble: 60 x 3
##    subject      A      B
##      &lt;int&gt;  &lt;dbl&gt;  &lt;dbl&gt;
##  1       1 -0.500 -0.500
##  2       2  0.500 -0.500
##  3       3 -0.500  0.500
##  4       4  0.500  0.500
##  5       5 -0.500 -0.500
##  6       6  0.500 -0.500
##  7       7 -0.500  0.500
##  8       8  0.500  0.500
##  9       9 -0.500 -0.500
## 10      10  0.500 -0.500
## # ... with 50 more rows</code></pre>
<p>Notice that we defined our two condition columns with the values of -.5 and .5. Think back to how this is modelled in a linear model in R. What might the intercept term be? It will be the mean across both conditions.</p>
<p>Next, we need to set up the coefficients and error term for our model. We want the intercept to be 400, a shift in A to be the intercept + 30, a shift in B to be the intercept - 50, and the interaction term to be the intercept - 40. Finally, our error term has a mean of 0 and standard deviation of 40.</p>
<p>We then create our data using the formula for the linear model, and add this to our data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># set up coefficients</span>
alpha =<span class="st"> </span><span class="dv">400</span>
beta1 =<span class="st"> </span><span class="dv">30</span>
beta2 =<span class="st"> </span>-<span class="dv">50</span>
beta3 =<span class="st"> </span>-<span class="dv">40</span>
err &lt;-<span class="st"> </span><span class="kw">rnorm</span>(n, <span class="dv">0</span>, <span class="dt">sd =</span> <span class="dv">40</span>)

<span class="co"># create data from the linear model</span>
data$y &lt;-<span class="st"> </span>alpha +<span class="st"> </span>(beta1*data$A) +<span class="st"> </span>(beta2*data$B) +<span class="st"> </span>(beta3*data$A*data$B) +<span class="st"> </span>err

<span class="co"># see the data</span>
data</code></pre></div>
<pre><code>## # A tibble: 60 x 4
##    subject      A      B     y
##      &lt;int&gt;  &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1       1 -0.500 -0.500   421
##  2       2  0.500 -0.500   472
##  3       3 -0.500  0.500   408
##  4       4  0.500  0.500   443
##  5       5 -0.500 -0.500   423
##  6       6  0.500 -0.500   479
##  7       7 -0.500  0.500   405
##  8       8  0.500  0.500   386
##  9       9 -0.500 -0.500   498
## 10      10  0.500 -0.500   428
## # ... with 50 more rows</code></pre>
<p>Let’s see how this data would look when modelled.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">fit &lt;-<span class="st"> </span><span class="kw">lm</span>(y ~<span class="st"> </span>A *<span class="st"> </span>B, <span class="dt">data =</span> data)
<span class="kw">summary</span>(fit)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ A * B, data = data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -108.540  -30.991    8.045   24.951   89.673 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  401.193      5.694  70.456  &lt; 2e-16 ***
## A             17.397     11.388   1.528   0.1322    
## B            -55.695     11.388  -4.890 8.85e-06 ***
## A:B          -47.358     22.777  -2.079   0.0422 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 44.11 on 56 degrees of freedom
## Multiple R-squared:  0.3532, Adjusted R-squared:  0.3185 
## F-statistic: 10.19 on 3 and 56 DF,  p-value: 1.868e-05</code></pre>
<p>Finally, we need to fit a model to our simulated data and extract the <em>p</em>-value. We need to do this fitting and extracting process several times before we can calculate our power to detect an effect. However, we need to know which effect we’re interested in detecting. Is it just an effect of A, B, or the interaction? That choice is up to you, but for now we’ll simply look at the probability to detect an effect for the interaction.</p>
<p>Thankfully, we can save on writing long functions and/or loops when we have some data like this by fitting our model once, and then using the <code>simulate()</code> function in R.</p>
<p>In this function, we need to pass our original data and model fit. We then create new data from our original data, but with a simulated response variable (<code>sim_y</code>) made from the <code>simulate()</code> function which is applied to our original model. We then refit the model with our new data and response variable, and we use a helper function <code>broom::tidy()</code> which puts model outputs in a nice table so we can easily select the <em>p</em>-value for the 4th row (i.e. the interaction). Try running <code>str()</code> on both <strong>fit</strong> and <strong>tidy_table</strong> to see what I mean.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">simulate_model_fit &lt;-<span class="st"> </span>function(data, model_fit) {
  <span class="co"># simulate data and add to tibble</span>
  new_data &lt;-<span class="st"> </span><span class="kw">mutate</span>(data, <span class="dt">sim_y =</span> <span class="kw">simulate</span>(fit)$sim_1)
  
  <span class="co"># refit model</span>
  refit_model &lt;-<span class="st"> </span><span class="kw">lm</span>(sim_y ~<span class="st"> </span>A *<span class="st"> </span>B, <span class="dt">data =</span> new_data)
  
  <span class="co"># extract p-value for interaction</span>
  broom::<span class="kw">tidy</span>(refit_model)$p.value[<span class="dv">4</span>]
}</code></pre></div>
<p>Finally, we can use <code>replicate()</code> to do this process however many times we’d like. We then calculate the power by seeing how often we find <em>p</em>-values below 0.05 for the interaction term.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">complex_power &lt;-<span class="st"> </span><span class="kw">replicate</span>(<span class="dv">1000</span>, <span class="kw">simulate_model_fit</span>(data, fit))
<span class="kw">mean</span>(complex_power &lt;<span class="st"> </span>.<span class="dv">05</span>)</code></pre></div>
<pre><code>## [1] 0.529</code></pre>
<p>Nice, we have very high power for this study!</p>
<p>Feel free to reuse and adapt the script above to your own needs. Try looking at the impact of inputting different parameter estimates and designs.</p>
</div>
</div>
</div>
<div id="performing-power-analyses-from-packages" class="section level2">
<h2><span class="header-section-number">8.4</span> Performing Power Analyses from Packages</h2>
<p>The first option of calculating power through simulation is very flexible, and I think it helps you to think more deeply about your data when compared to running canned power analyses. Also, there aren’t many ways to easily calculate power with mixed effects models, and so simulation is our best bet at the moment. However, there are options out there if you want to calculate power for most designs without the need to do simulation.</p>
<p>R has an inbuilt power analysis function for <em>t</em>-tests called <code>power.t.test()</code>, and for ANOVAs called <code>power.anova.test()</code>.</p>
<p>Let’s see how the ANOVA function works, and you can work back to the <em>t</em>-test function if necessary. In this function, we just have to define the number of groups we have, the number of observations in each group (typically participants in psychology), and the variance for any between-subjects and within-subjects variables.</p>
<p>Making the below assumptions, it looks like our study is overpowered.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">power.anova.test</span>(<span class="dt">groups =</span> <span class="dv">4</span>, <span class="dt">n =</span> <span class="dv">20</span>, <span class="dt">between.var =</span> <span class="dv">1</span>, <span class="dt">within.var =</span> <span class="dv">3</span>)</code></pre></div>
<pre><code>## 
##      Balanced one-way analysis of variance power calculation 
## 
##          groups = 4
##               n = 20
##     between.var = 1
##      within.var = 3
##       sig.level = 0.05
##           power = 0.9679022
## 
## NOTE: n is number in each group</code></pre>
<p>Alternatively, we can predefine our desired power (typically 80% in psychology), and this will work out the number of participants needed per group.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">power.anova.test</span>(<span class="dt">groups =</span> <span class="dv">4</span>, <span class="dt">between.var =</span> <span class="dv">1</span>, <span class="dt">within.var =</span> <span class="dv">3</span>, <span class="dt">power =</span> .<span class="dv">80</span>)</code></pre></div>
<pre><code>## 
##      Balanced one-way analysis of variance power calculation 
## 
##          groups = 4
##               n = 11.92613
##     between.var = 1
##      within.var = 3
##       sig.level = 0.05
##           power = 0.8
## 
## NOTE: n is number in each group</code></pre>
<p>Great, it looks like we only need 12 people in each group to achieve a power of 80%.</p>
<p>There are other options which allow you to specify means or effect sizes to determine power, and as such these may be more user friendly. One option is the <code>pwr</code> package, which contains a number of functions for calcualting power with different designs. Have a look at this in your own time to see if it will be useful to you.</p>
</div>
<div id="exercises-7" class="section level2">
<h2><span class="header-section-number">8.5</span> Exercises</h2>
<div id="introduction-and-setup-1" class="section level3">
<h3><span class="header-section-number">8.5.1</span> Introduction and Setup</h3>
<p>For these exercises, we will look at the core concepts from this lesson. Here, you’ll make your own data using simulation-based techniques, and you’ll use those same techniques to calculate power for your design.</p>
</div>
<div id="question-1-7" class="section level3">
<h3><span class="header-section-number">8.5.2</span> Question 1</h3>
<p>Create some data for 60 participants (split into two groups), A and B. Save this as a tibble called <strong>sim_data</strong>.</p>
<p>Make a column containing the subject ID (called <strong>subject_id</strong>), a column for condition (called <strong>condition</strong>), and a column for the outcome (called <strong>outcome</strong>).</p>
<p>You will have to use the <code>seq()</code> function to make sequential numbers for the subject ID, the <code>rep()</code> function with the <code>c()</code> function to make the conditions, and the <code>rnorm()</code> function with the <code>c()</code> function to make the scores.</p>
<p>For the outcome column, we want a mean of 180, and standard deviation of 10 for the first group, and a mean of 190 and standard deviation of 10 for the second group.</p>
</div>
<div id="question-2-7" class="section level3">
<h3><span class="header-section-number">8.5.3</span> Question 2</h3>
<p>Generate summary statistics for the data set. We want means, SDs, and ns for the table of summary statistics. How do these means and standard deviations match the sampling procedure? Are you surprised at all by these values?</p>
</div>
<div id="question-3-7" class="section level3">
<h3><span class="header-section-number">8.5.4</span> Question 3</h3>
<p>Conduct an independent samples <em>t</em>-test looking at differences in the scores across the two groups.</p>
</div>
<div id="question-4-7" class="section level3">
<h3><span class="header-section-number">8.5.5</span> Question 4</h3>
<p>Turn the sampling procedure into a function called <code>sim_data</code>.</p>
<p>The arguments the function can take are:</p>
<ul>
<li>n_one: the number of observations for group 1</li>
<li>n_two: the number of observations for group 2</li>
<li>mean_one: the mean score in the population for group 1</li>
<li>mean_two: the mean score in the population for group 2</li>
<li>sd_one: the standard deviation in the population for group 1</li>
<li>sd_two: the standard deviation in the population for group 2</li>
</ul>
<p>Remember that these arguments come within the paretheses after the blue <code>function</code> part.</p>
<p><em>Hint</em>: Just copy and paste your code for 1, and replace the things you want to vary with the name of a variable that will define your function arguments.</p>
<p>Test that your function works by passing it some parameters. Pass it an n of 80 for both groups, a mean of 200 and SD of 10 for group 1, and a mean of 195 and SD for 10 for group 2.</p>
<p>Assign the outcome of your function to an object to save the outcome. Call this object <strong>new_data</strong>.</p>
</div>
<div id="question-5-7" class="section level3">
<h3><span class="header-section-number">8.5.6</span> Question 5</h3>
<p>Make a new function called <code>sim_test</code>, which uses your simulation function from above to make some data before it runs an independent samples <em>t</em>-test on the data. Finally, this function should output the <em>p</em>-value from the <em>t</em>-test. Note that this function should take as arguments the same arguments from the function in question 4. Can you figure out why this is the case?</p>
<p>Test that your function works by passing it the same arguments as in question 4, and assign this to the object <code>new_data_p</code>.</p>
</div>
<div id="question-6-7" class="section level3">
<h3><span class="header-section-number">8.5.7</span> Question 6</h3>
<p>Calculate the power for your study based on the parameters from question 4 and 5 (ns of 80; mean of 200 and 195, SDs of 10). Do so by running your function 1000 times and capturing the p-values. Assign this to the object <strong>power_data</strong>.</p>
<p><em>Top Tip</em>: If you need to test your code (which you should), make sure you use a low number like 10 for your replications before running it 1000 times to answer this question. This will save time and avoid flooding your console etc. if you make a mistake.</p>
</div>
<div id="question-7-6" class="section level3">
<h3><span class="header-section-number">8.5.8</span> Question 7</h3>
<p>Calculate the power of your study from the <em>p</em>-values in question 6. What is the power for your study? (Your values will differ from mine as we aren’t using <code>set.seed()</code>, but we’re instead using proper random sampling.)</p>
</div>
<div id="question-8-6" class="section level3">
<h3><span class="header-section-number">8.5.9</span> Question 8</h3>
<p>Make a plot of the <em>p</em>-values from your simulated data. Make this with a binwidth of 0.05, a boundary of 0 and with white bars with a black border.</p>
<p>Also, make sure that the breaks happen at every 0.05 tick along the x-axis.</p>
<p>What percentage of your data lie below the 0.05 line? What does this correspond to?</p>
</div>
<div id="question-9-6" class="section level3">
<h3><span class="header-section-number">8.5.10</span> Question 9</h3>
<p>Remake your data from question 6, only with means of 200 in each group. Call this <strong>power_data_null</strong>.</p>
<p>Then calculate the power as in question 7, and plot your data as in question 8.</p>
<p><em>Note</em>: The sampling procedure may take a while to run.</p>
<p>What percentage of the data fall below the 0.05 line on the plot? What does this correspond to? What percentage falls within each bin above the 0.05 line? Are you surprised at the distribution of the <em>p</em>-values?</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="advanced-statistical-tests.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="mixed-effects-models.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
